### ISSUE TITLE
Root node not returned from parser

### ISSUE THREAD

**Issue by mollentze** [sabre-io/xml#172]
This issue is probably related to [#162](https://github.com/sabre-io/xml/issues/162).

The root node is omitted from the array returned from the `parse()` method of `Sabre\Xml\Service`.

As a result, it's not possible to access the root node or its attribute values from the parsed document.

Only the name of the root node can be accessed by passing the `&$rootElementName` parameter to the `parse()` method.

The parse() method currently returns the **value** of the root node:

```php
return $result['value'];
```

However, the parser should probably **return** the root node?

```php
return $result;
```

To illustrate, consider the following code.

```php
$document = <<<XML
<?xml version="1.0"?>
<rootNode xmlns="http://example.org/ns" primary="first">
  <childNode secondary="second">
    <grandChildNode tertiary="third" />
    </childNode>
</rootNode>
XML;

$service = new Sabre\Xml\Service();
var_dump($service->parse($document));
```

The output is:

```
array(1) {
  [0]=>
  array(3) {
    ["name"]=>
    string(32) "{http://example.org/ns}childNode"
    ["value"]=>
    array(1) {
      [0]=>
      array(3) {
        ["name"]=>
        string(37) "{http://example.org/ns}grandChildNode"
        ["value"]=>
        NULL
        ["attributes"]=>
        array(1) {
          ["tertiary"]=>
          string(5) "third"
        }
      }
    }
    ["attributes"]=>
    array(1) {
      ["secondary"]=>
      string(6) "second"
    }
  }
}
```

**Comment by evert** [comment]
This is by design. Most XML documents *don't* have interesting information in the root element, so the library is optimized for this case.

The main advantage is it reduces one level of nesting.

The only case where this is really annoying, is if there's an important attribute on the root element. For those cases, I can offer 2 suggestions:

1. Use the elementMapper. I would generally recommend people move away from this array structure to a better defined document tree based on specific typed classes.
2. Use the `Reader` class directly, instead of going through the `Service` class.

**Comment by steve7n** [comment]
Might be a bit late to this, but you could add a temporary element to wrap everything

`<?xml version="1.0"?>
**<TemporaryNode>**
<rootNode xmlns="http://example.org/ns" primary="first">
  <childNode secondary="second">
    <grandChildNode tertiary="third" />
    </childNode>
</rootNode>` 
**</TemporaryNode>**

Add it just when you read it with the parse() method, then it will return everything.
